version: '3'

services:
  redis:
    container_name: redis
    image: redis:5
    restart: always
    # command: redis-server --appendonly yes --requirepass xxxxxx  # with password
    command: redis-server --appendonly yes
    ports:
    - "6379:6379"
    volumes:
    - ./redis:/data
