version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=xxxxxx
    - TZ=Asia/Shanghai
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
    - "3306:3306"
    volumes:
    - ./mysql:/var/lib/mysql
