apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: infra
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mysql
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
        args: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: data
        env:
        - name: TZ
          value: Asia/Shanghai
        - name: MYSQL_ROOT_PASSWORD
          value: xxxxxx

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: infra
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
    #nodePort: 30098

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql
  namespace: infra
spec:
  accessModes:
  - ReadWriteOnce
  resources:
   requests:
     storage: 50Gi
  storageClassName: hostpath
