version: '3'

services:
  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.5.8
    restart: always
    ports:
    - "2181:2181"
    volumes:
    - ./data/data:/data
    - ./data/datalog:/datalog
    - ./logs:/logs
    environment:
    - TZ=Asia/Shanghai
    - ZOO_MAX_CLIENT_CNXNS=200
    - ZOO_ADMINSERVER_ENABLED=false
    - ZOO_LOG3J_PROP=INFO,ROLLINGFILE
