version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    container_name: jenkins
    privileged: true
    extra_hosts:
    - "jcr.xxx.com:192.168.79.97"
    user: root
    ports:
    - "28080:8080"
    - "50000:50000"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./bin/docker:/usr/bin/docker
    - ./data:/var/jenkins_home
    environment:
    - JAVA_OPTS=-Duser.timezone=Asia/Shanghai
